export const LOAD_MY_TICKETS_SUCCESS = 'LOAD_MY_TICKETS_SUCCESS';
export const LOAD_MY_TICKETS_FAIL = 'LOAD_MY_TICKETS_FAIL';
export const LOAD_TICKET_DETAIL_SUCCESS = 'LOAD_TICKET_DETAIL_SUCCESS';
export const LOAD_TICKET_DETAIL_FAIL = 'LOAD_TICKET_DETAIL_FAIL';
