export const SEARCH_CONTENT_SUCCESS = 'SEARCH_CONTENT_SUCCESS';
export const SEARCH_CONTENT_FAIL = 'SEARCH_CONTENT_FAIL';
export const SEARCH_LOCATION_SUCCESS = 'SEARCH_LOCATION_SUCCESS';
export const SEARCH_LOCATION_FAIL = 'SEARCH_LOCATION_FAIL';
export const SEARCH_CONTENT_CLEAR = 'SEARCH_CONTENT_CLEAR';
export const SEARCH_LOCATION_CLEAR = 'SEARCH_LOCATION_CLEAR';