export const LOAD_MY_STATISTICS_SUCCESS = 'LOAD_MY_STATISTICS_SUCCESS';
export const LOAD_MY_STATISTICS_FAIL = 'LOAD_MY_STATISTICS_FAIL';

export const LOAD_PERFORMANCE_STATS_SUCCESS = 'LOAD_PERFORMANCE_STATS_SUCCESS';
export const LOAD_PERFORMANCE_STATS_FAIL = 'LOAD_PERFORMANCE_STATS_FAIL';

export const LOAD_MOVIE_STATS_SUCCESS = 'LOAD_MOVIE_STATS_SUCCESS';
export const LOAD_MOVIE_STATS_FAIL = 'LOAD_MOVIE_STATS_FAIL';

export const LOAD_SPORTS_STATS_SUCCESS = 'LOAD_SPORTS_STATS_SUCCESS';
export const LOAD_SPORTS_STATS_FAIL = 'LOAD_SPORTS_STATS_FAIL';